AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false
