version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  sidekiq:
    env_file:
      - .env
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - default

  redis:
    image: redis:4-alpine
    networks:
      - default

volumes:
  db_data:

networks:
  default:
