version: '3'

services:
  app:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - default

  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  db_data:

networks:
  default:
